# Starter pipeline
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      git config --global user.email "t-aksh@microsoft.com"
      git config --global user.name "Akash Sharma"
      
      git reset --soft HEAD~1
      Write-Host "git reset --soft HEAD~1"
      
      Write-Host "git status"
      $ChangedFiles = $(git status --porcelain)
      foreach ($ChangedFile in $ChangedFiles)
      {
      Write-Host $ChangedFile
      }
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
